enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "inotia00/revanced-patches"
rv-brand = "ReVanced eXtended"
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"                                                   
excluded-patches = ""                                                 
included-patches = "" 
patcher-args = " -e 'GmsCore support' "
version = "auto"                                                      
exclusive-patches = false                                             
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rvx"

include-stock = false
riplib = false
